### ISSUE TITLE
PVC volume mount source path is changed in Peer Pod

### ISSUE THREAD

**Issue by genjuro214** [confidential-containers/cloud-api-adaptor#128]
We are trying to create a container with PVC volume in Peer Pod. The container (`nginx`) will be running with csi driver (`ibm-vpc-block-podvm-node-driver`) and csi wrapper (`hyperpcons-csi-podvm-wrapper`) together. The pod definition would be:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: kube-system
spec:
  runtimeClassName: kata
  containers:
    - name: ibm-vpc-block-podvm-node-driver
      env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      envFrom:
        - configMapRef:
            name: ibm-vpc-block-csi-configmap
      image: gcr.io/k8s-staging-cloud-provider-ibm/ibm-vpc-block-csi-driver:master
      imagePullPolicy: Always
      securityContext:
        privileged: true
        runAsNonRoot: false
        runAsUser: 0
      ports:
        - containerPort: 9808
          name: healthz
          protocol: TCP
      volumeMounts:
        - name: kubelet-data-dir
          mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
        - mountPath: /tmp
          name: plugin-dir
        - mountPath: /dev
          name: device-dir
        - mountPath: /etc/udev
          name: etcudevpath
        - mountPath: /run/udev
          name: runudevpath
        - mountPath: /lib/udev
          name: libudevpath
        - mountPath: /sys
          name: syspath
        - mountPath: /etc/storage_ibmc
          name: customer-auth
          readOnly: true
    - name: hyperpcons-csi-podvm-wrapper
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAME_SPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      args:
        - /usr/bin/hyperpcons-csi-podvm-wrapper
        - --v=5
        - --endpoint=/tmp/csi-podvm-wrapper.sock
        - --target-endpoint=/tmp/csi.sock
        - --namespace=kube-system
      image: liudali/hyperpcons-csi-podvm-wrapper:dev
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /tmp
          name: plugin-dir
    - name: nginx
      image: nginx
      volumeMounts:
        - name: my-volume
          mountPath: /mount-path
  serviceAccountName: ibm-vpc-block-node-sa
  volumes:
    - name: kubelet-data-dir
      hostPath:
        path: /var/lib/kubelet # OpenShift worker, for kubernetes /var/data/kubelet
        type: Directory
    - emptyDir: {}
      name: plugin-dir
    - hostPath:
        path: /dev
        type: Directory
      name: device-dir
    - hostPath:
        path: /etc/udev
        type: Directory
      name: etcudevpath
    - hostPath:
        path: /run/udev
        type: Directory
      name: runudevpath
    - hostPath:
        path: /lib/udev
        type: Directory
      name: libudevpath
    - hostPath:
        path: /sys
        type: Directory
      name: syspath
    - name: customer-auth
      secret:
        secretName: storage-secret-store
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
```

The problem is, the source path of the PVC mount (`my-volume`) is changed by **kata shim**. For example,

For `ibm-vpc-block-podvm-node-driver`, it requires volume `kubelet-data-dir`:
```
volumeMounts:
        - name: kubelet-data-dir
          mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
...
volumes:
    - name: kubelet-data-dir
      hostPath:
        path: /var/lib/kubelet
        type: Directory
```

In original OCI spec, the mount should be:
```
{
      "destination": "/var/lib/kubelet",
      "type": "bind",
      "source": "/var/lib/kubelet",
      "options": [
          "rbind",
          "rshared",
          "rw"
      ]
  },
```

But the source is changed on peer pod VM:
```
{
      "destination": "/var/lib/kubelet",
      "type": "bind",
      "source": "/run/kata-containers/shared/containers/0b616ad087dfa361d6220c69a3e2d4d5c3b140d6515364f8be1e3031d173ed02-a0190fb5b10de6d6-kubelet",
      "options": [
        "rbind",
        "rshared",
        "rw"
      ]
    },
```

---

For **nginx** container, it requires volume from pvc:
```
volumeMounts:
        - name: my-volume
          mountPath: /mount-path
...
- name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
```

In original OCI spec, the mount should be:
```
{
    "destination": "/mount-path",
    "type": "bind",
    "source": "/var/lib/kubelet/pods/72dd8781-8df4-4c23-aa59-96c8acb21d10/volumes/kubernetes.io~csi/pvc-0b656c19-cf4a-469d-9e20-45853f98d43b/mount",
    "options": [
        "rbind",
        "rprivate",
        "rw"
    ]
},
```

But the source is changed on peer pod VM:
```
{
      "destination": "/mount-path",
      "type": "bind",
      "source": "/run/kata-containers/shared/containers/ed6aee1b898e0a02ac4aac690dd7e9a8b4f136d93c184d6138d6c2b6333034a5-a5f6aa6a56100f8a-mount-path",
      "options": [
        "rbind",
        "rslave",
        "rw"
      ]
    },
```

That's because **kata shim** need copy files from the source on worker node to the shared dir on peer pod VM. The codes can be found in:
https://github.com/yoheiueda/kata-containers/blob/CCv0-peerpod/src/runtime/virtcontainers/container.go#L427
https://github.com/yoheiueda/kata-containers/blob/CCv0-peerpod/src/runtime/virtcontainers/fs_share_linux.go#L273

The problem is, `ibm-vpc-block-csi-driver` will always mount the device to the sub dir under "/var/lib/kubelet", so on peer pod VM host the device will be mounted to path like: `/run/kata-containers/shared/containers/0b616ad087dfa361d6220c69a3e2d4d5c3b140d6515364f8be1e3031d173ed02-a0190fb5b10de6d6-kubelet/pods/500a05fd-d1b8-4654-bd26-72bd1f65eb8c/volumes/kubernetes.io~csi/pvc-0b656c19-cf4a-469d-9e20-45853f98d43b/mount`

but the mounted device can not be accessed by `nginx` container that mounts on "/run/kata-containers/shared/containers/ed6aee1b898e0a02ac4aac690dd7e9a8b4f136d93c184d6138d6c2b6333034a5-a5f6aa6a56100f8a-mount-path"
