### ISSUE TITLE
peer-pods with corrupted images  - fail to cleanup (Seen on Libvirt)

### ISSUE THREAD

**Issue by davidhadas** [confidential-containers/cloud-api-adaptor#1737]
To reproduce on libvirt: 

1. Load a broken image file
```
echo "abc" > test.qcow2
IMAGE=<f.ll/path/to/test.qcow2>
virsh vol-delete podvm-base.qcow2 --pool default
virsh -c qemu:///system vol-create-as --pool default --name podvm-base.qcow2 --capacity 20G --allocation 2G --prealloc-metadata --format qcow2
virsh -c qemu:///system vol-upload --vol podvm-base.qcow2 $IMAGE --pool default --sparse

```
2. Create a sample.yaml file
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: quay.io/prometheus/busybox
    name: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  runtimeClassName: kata-remote
  ```
  
  3. `kubectl apply -f ./sample.yaml`
  
 4. Open a second terminal with `watch virsh list`
 - Every 4 min a new peer pod gets created, the previous one never cleaned
 
 5. `kubectl delete -f ./sample.yaml; kubectl apply -f ./sample.yaml`
 - Every time you delete and recreate the pod, a new peer pod gets created, the previous one never cleaned (note that delete may take up to 4 min to complete)
 
 
 
 Results during a final deletion of a pod:
 ```
 ubuntu@coco:~$ virsh list
 Id    Name                     State
-----------------------------------------
 1     peer-pods-ctlplane-0     running
 2     peer-pods-worker-0       running
 557   podvm-busybox-6dba907e   running
 558   podvm-busybox-77b23ebe   running
 559   podvm-busybox-914cf1b9   running
 560   podvm-busybox-76a9b937   running
 561   podvm-busybox-17577d09   running
 562   podvm-busybox-59aa270a   running
 563   podvm-busybox-44b653c1   running
 564   podvm-busybox-0ec292ad   running

ubuntu@coco:~$ kubectl get pods
NAME      READY   STATUS        RESTARTS   AGE
busybox   0/1     Terminating   0          5m12s

ubuntu@coco:~$ kubectl get peerpods
No resources found in default namespace.
```

---
Also, the adaptor continues to look for peerpods after they get deleted or fail....
See comment below with an example log
(May be an unrelated issue)
