### ISSUE TITLE
x86 operator install cannot work on IBM Cloud

### ISSUE THREAD

**Issue by genjuro214** [confidential-containers/cloud-api-adaptor#491]
I'm following this [install guide](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/install/README.md) to install x86 operator on IBM Cloud:
1. create an IBM IKS cluster
2. label the node with "worker" role
3. configure "install/overlays/ibmcloud/kustomization.yaml"
4. `export CLOUD_PROVIDER=ibmcloud` make deploy

The problem is, the runtimeclass resources are not created in cluster, and missing pods "cc-operator-daemon-install-" and "cc-operator-pre-install-daemon" under `confidential-containers-system` namespace.

---

Checking logs, the Daemonset **cc-operator-daemon-install** is created in `kube-system` namespace:
```
# kubectl logs cc-operator-controller-manager-6886d9466f-2slwn -n confidential-containers-system -c manager
...
1.6722147997112765e+09	INFO	Creating a new installation Daemonset	{"controller": "ccruntime", "controllerGroup": "confidentialcontainers.org", "controllerKind": "CcRuntime", "ccRuntime": {"name":"ccruntime-sample-ibmcloud"}, "namespace": "", "name": "ccruntime-sample-ibmcloud", "reconcileID": "35cea51b-8e85-408e-b609-8683ea8b1bd3", "ds.Namespace": "kube-system", "ds.Name": "cc-operator-daemon-install"}

# kubectl get ds -A
NAMESPACE                        NAME                                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                            AGE
confidential-containers-system   cloud-api-adaptor-daemonset-ibmcloud   1         1         1       1            1           node-role.kubernetes.io/worker=          72m
kube-flannel                     kube-flannel-ds                        2         2         2       2            2           <none>                                   90m
kube-system                      cc-operator-daemon-install             0         0         0       0            0           node-role.kubernetes.io/worker=          72m
kube-system                      cc-operator-daemon-uninstall           0         0         0       0            0           katacontainers.io/kata-runtime=cleanup   72m
kube-system                      ext-res-updater                        1         1         1       1            1           node-role.kubernetes.io/worker=          66m
```

There is no pod created for the Daemonset, and the error is:
```
# kubectl describe ds cc-operator-daemon-install -n kube-system
...
Events:
  Type     Reason        Age                  From                  Message
  ----     ------        ----                 ----                  -------
  Warning  FailedCreate  101s (x22 over 73m)  daemonset-controller  Error creating: pods "cc-operator-daemon-install-" is forbidden: error looking up service account kube-system/cc-operator-controller-manager: serviceaccount "cc-operator-controller-manager" not found
```

Because the service account "cc-operator-controller-manager" is not in the `kube-system` namespace:
```
# kubectl get serviceaccount -A | grep cc-operator-controller-manager
confidential-containers-system   cc-operator-controller-manager         0         75m
```

**Comment by genjuro214** [comment]
To fix the problem, we can set correct namespace for the daemon set via env variable **CCRUNTIME_NAMESPACE**

Modify https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/install/yamls/deploy.yaml:
```diff
# git diff install/yamls/deploy.yaml
diff --git a/install/yamls/deploy.yaml b/install/yamls/deploy.yaml
index fcb61b5..afd20d9 100644
--- a/install/yamls/deploy.yaml
+++ b/install/yamls/deploy.yaml
@@ -255,6 +255,11 @@ spec:
         command:
         - /manager
         image: quay.io/confidential-containers/operator:latest
+        env:
+        - name: CCRUNTIME_NAMESPACE
+          valueFrom:
+            fieldRef:
+              fieldPath: metadata.namespace
         livenessProbe:
           httpGet:
             path: /healthz
```

**Comment by genjuro214** [comment]
With the fix above, operator can be installed on the IKS cluster, and runtimeclass `kata` is created.

Try to create a sample pod with runtimeclass `kata`. 

The peer pod VM can be created, but the connection between worker and pod VM can not be established.

Check the log of pod **cloud-api-adaptor-daemonset-ibmcloud-xxx**:
```
2022/12/29 07:09:59 [adaptor/proxy] Listening on /run/peerpod/pods/72759eef66b8cf8c1dd634b968ed2f13dc68f24732444abff0f4429df0c6077f/agent.ttrpc
2022/12/29 07:13:52 [adaptor/proxy] shutting down socket forwarder
```

It hangs in code of [proxy.Start()](https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/pkg/adaptor/proxy/proxy.go#L130)

According to debugging, the invoking doesn't return when get connection to an unix socket:
https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/pkg/adaptor/proxy/proxy.go#L110

The socket is `/run/peerpod/cri-runtime.sock`, it seems mounted from host `/run/containerd/containerd.sock`. For details, pls refer to:
https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/install/overlays/ibmcloud/cri_runtime_endpoint.yaml

Not sure why the mounted socket cann't be connected in pod **cloud-api-adaptor-daemonset-ibmcloud**.

I try to modify cri_runtime_endpoint.yaml, and mount the host path **/run/containerd** directly, not just the socket:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-api-adaptor-daemonset
  namespace: confidential-containers-system
  labels:
    app: cloud-api-adaptor
spec:
  template:
    spec:
      containers:
      - name: cloud-api-adaptor-con
        env:
        - name: CRI_RUNTIME_ENDPOINT
          value: /run/containerd/containerd.sock
        volumeMounts:
        - mountPath: /run/containerd # in-container CRI_RUNTIME_ENDPOINT default
          name: cri-runtime-endpoint
      volumes:
      - name: cri-runtime-endpoint
        hostPath:
          path: /run/containerd # SET! (crio's default: /var/run/crio/crio.sock)
          type: ""
```

It seems working!
