### ISSUE TITLE
Operator: can't connect to cri-runtime.sock in cloud-api-adaptor-con container

### ISSUE THREAD

**Issue by genjuro214** [confidential-containers/cloud-api-adaptor#530]
The problem is found when fixing #491. Pls refer to comment: https://github.com/confidential-containers/cloud-api-adaptor/issues/491#issuecomment-1371880366

The problem seems not always reproduced, pls refer to comments in PR https://github.com/confidential-containers/cloud-api-adaptor/pull/494

Just create this issue, and monitor if the problem really exists.

**Comment by jtumber-ibm** [comment]
I've also found switching cri_runtime_endpoint.yaml to

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-api-adaptor-daemonset
  namespace: confidential-containers-system
  labels:
    app: cloud-api-adaptor
spec:
  template:
    spec:
      containers:
      - name: cloud-api-adaptor-con
        env:
        - name: CRI_RUNTIME_ENDPOINT
          value: /run/containerd/containerd.sock
        volumeMounts:
        - mountPath: /run/containerd # in-container CRI_RUNTIME_ENDPOINT default
          name: cri-runtime-endpoint
      volumes:
      - name: cri-runtime-endpoint
        hostPath:
          path: /run/containerd # SET! (crio's default: /var/run/crio/crio.sock)
          type: ""
```

Fixes the problem

**Comment by mattarnoatibm** [comment]
I also reproduced this problem using the default cri_runtime_endpoint.yaml and fixed it by changing it to

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-api-adaptor-daemonset
  namespace: confidential-containers-system
  labels:
    app: cloud-api-adaptor
spec:
  template:
    spec:
      containers:
      - name: cloud-api-adaptor-con
        env:
        - name: CRI_RUNTIME_ENDPOINT
          value: /run/containerd/containerd.sock
        volumeMounts:
        - mountPath: /run/containerd # in-container CRI_RUNTIME_ENDPOINT default
          name: cri-runtime-endpoint
      volumes:
      - name: cri-runtime-endpoint
        hostPath:
          path: /run/containerd # SET! (crio's default: /var/run/crio/crio.sock)
          type: ""
```
