### ISSUE TITLE
Add versioning system for dependencies

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#598]
At the moment of the components we pull in (most notably to the podvm image) are either not versioned (e.g. kata-agent, attestation-agent)- so we pull in the latest code, or versions in particular files (skopeo, umoci, pause image, ubuntu version). In order to ensure our 'supply chain' is reliable and trusted and in future to enable us to have reproducible builds, we should consider adding a centralised place to control the versions of files, maybe similar to [versions.yaml](https://github.com/kata-containers/kata-containers/blob/CCv0/versions.yaml) that kata-containers has.

**Comment by jtumber-ibm** [comment]
Example

```yaml
---
cloud-img:
  - distro: ubuntu
    architecture: amd64
    source:
      url: https://cloud-images.ubuntu.com/releases/focal/release-20230107/ubuntu-20.04-server-cloudimg-amd64.img
      checksum: 3895e38566e5c2c019f5c6f825ab7570ee34dac6b9142fab0c7e5a78084c4280
  - distro: ubuntu
    architecture: s390x
    source:
      url: https://cloud-images.ubuntu.com/releases/focal/release-20230107/ubuntu-20.04-server-cloudimg-s390x.img
      checksum: 24673aa86785573d3a92e15166ff81beff88cbb0abc01938f156eb1332e87cd3
```
