### ISSUE TITLE
Kubernetes Resource management

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#7]
k8s resource management with peer-pods (remote hypervisor) is still unclear. This issue is a placeholder to summarize the investigations on different approaches and eventual implementation.

Slide deck: https://docs.google.com/presentation/d/1GWNgQdRC5WxrXz_0XCW3DGIfzQHkO4MaN-8BlRPuTDc/edit?usp=sharing
different approaches - https://docs.google.com/document/d/1mb4Ig_kjAgwson453ydin0_jipCf3umH-hk9evZNAao/edit?usp=sharing
admission controller - https://docs.google.com/document/d/1RjJ8fYKfIEIvDUhVhsYEElyaJlm_2BjzwB1BC1sl0hw/edit?usp=sharing

**Comment by bpradipt** [comment]
Adding some initial thoughts here for kickstarting the discussions.   I can also put this in a google doc as well if it makes it easier for commenting and discussion. Please let me know.

Few options that comes to my mind for potential investigation.

**Option-1**
Using virtual kubelet (VK) approach to manage the peer-pods capacity. `VK` talks to Kata runtime to spin up peer-PODs. 
There won't be any UX changes from an end-user standpoint. 

**Option-2**
Using custom scheduler.
A potential downside to this approach is that the UX changes for the end-user. The end user needs to explicitly specify the custom scheduler.  
Need more investigation on whether this approach is feasible for the peer-pods case.

**Option-3**
Using a custom resource (CR). The custom resource controller manages the capacity and accounting.
A potential downside to this approach is that the UX changes for the end-user. The end user needs to create a CR instead of a regular K8s POD. Advantage being, this approach can make it easier to manage aspects like cloud provider configuration, quota etc.


cc @fidencio @stevenhorsman @magowan

**Comment by fidencio** [comment]
cc @kad @mythi

**Comment by bpradipt** [comment]
Adding another option - Option-4 
Using an admission controller to accept/deny the POD request based on available peer-pods capacity.

If peer-pod resource request is within the limits, the admission controller removes the resource requests and replaces it with an annotation specifying the instance type that satisfies the resource requests. This can be used by the peer-pods binary to spin up a correctly sized instance

**Comment by surajssd** [comment]
We can create a namespaced CR that can selects pods based on labels. And this CR can define things related to the machine type we would want. So for the user they have to add another label defined in CR and the cloud-api-adapter makes decision based on the information from the CR.

Annotations can be limiting compared to a full fledged CR.

---

Adding an admission controller could be a good UX, where things fail early if there is no capacity. But this also makes the pod creation a synchronous process. And if it were to be handled by the cloud-api-adaptor things might fail later at the pod creation time hence it will be asynchronous.

**Comment by bpradipt** [comment]
> We can create a namespaced CR that can selects pods based on labels. And this CR can define things related to the machine type we would want. So for the user they have to add another label defined in CR and the cloud-api-adapter makes decision based on the information from the CR.
> 
> Annotations can be limiting compared to a full fledged CR.
> 
> Adding an admission controller could be a good UX, where things fail early if there is no capacity. But this also makes the pod creation a synchronous process. And if it were to be handled by the cloud-api-adaptor things might fail later at the pod creation time hence it will be asynchronous.

Agree @surajssd .. CR definitely provides more flexibility. I also think it's better to try with few options and identify the practical issues.

**Comment by bpradipt** [comment]
Put the details in google doc, if it makes it easier for people to collaborate and comment.
different approaches - https://docs.google.com/document/d/1mb4Ig_kjAgwson453ydin0_jipCf3umH-hk9evZNAao/edit?usp=sharing
admission controller - https://docs.google.com/document/d/1RjJ8fYKfIEIvDUhVhsYEElyaJlm_2BjzwB1BC1sl0hw/edit# (edited)

**Comment by bpradipt** [comment]
Continuing the investigation on different approaches we found that coupling K8s extended resource management with mutating admission controller provides a good platform to get started. 

Example:
Advertise the peer-pods capacity as k8s extended resource

```
CPU capacity = 5
curl --header "Content-Type: application/json-patch+json" --request PATCH --data '[{"op": "add", "path": "/status/capacity/kata.peerpods.io~1vmcpu", "value": "5000"}]' http://localhost:8001/api/v1/nodes/webhook-control-plane/status

Mem capacity = 10Gi 

curl --header "Content-Type: application/json-patch+json" --request PATCH --data '[{"op": "add", "path": "/status/capacity/kata.peerpods.io~1vmmem", "value": "10737418240"}]'  http://localhost:8001/api/v1/nodes/webhook-control-plane/status

```
Looking at the node description shows the peer-pods resources
```


kubectl describe node webhook-control-plane | less

…
Capacity:
  cpu:                    64
  ephemeral-storage:      914690Mi
  hugepages-1Gi:          0
  hugepages-2Mi:          0
  kata.peerpods.io/vmcpu:  5k
  kata.peerpods.io/vmmem:  10737418240
  memory:                 394817768Ki
  pods:                   110
Allocatable:
  cpu:                    64
  ephemeral-storage:      914690Mi
  hugepages-1Gi:          0
  hugepages-2Mi:          0
  kata.peerpods.io/vmcpu:  5k
  kata.peerpods.io/vmmem:  10737418240
  memory:                 394817768Ki
  pods:                   110
…
```

The mutating admission controller will convert the container(s) resource request/limit to peer-pod resource request/limits.
Also suitable annotations are added to indicate the aggregate peer-pod VM resource required.  The annotations will be used by the peer-pods binary to create the right-sized VM instance. 

Let's consider the following runtimeClass definition
```
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: kata-peerpods
handler: kata-peerpods
overhead:
  podFixed:
    memory: "120Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    peer-pods: "true"
```

Let's consider the following POD specification (only key fields shown)
``` 
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  runtimeClassName: kata-peerpods
  containers:
...
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
```

The mutating admission controller modifies the pod upon admission (only key fields shown)
```
apiVersion: v1
kind: Pod
metadata:
  name: example
  annotations:
    kata.peerpods.io/vmcpu_total: "1000"
    kata.peerpods.io/vmmem_total: "2273312768"
spec:
  runtimeClassName: kata-peerpods
  containers:
…
    overhead:
      cpu: 250m
      memory: 120Mi
    resources:
      requests:
        kata.peerpods.io/vmcpu: "1000"
        kata.peerpods.io/vmmem: "2273312768"
      limits:
        kata.peerpods.io/vmcpu: "1000"
        kata.peerpods.io/vmmem: "2273312768"
```


Updated doc - 
https://docs.google.com/document/d/1RjJ8fYKfIEIvDUhVhsYEElyaJlm_2BjzwB1BC1sl0hw/edit?usp=sharing
